// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadGoalStage = {
/**
 * Stable user-visible identity. Revisions retain a stage's id.
 */
id: string, label: string, expectedResult: string,
/**
 * Unix seconds at which this deliverable is due.
 */
deadlineAt: number,
/**
 * Server-stamped Unix seconds when evidence was recorded.
 */
deliveredAt?: number,
/**
 * Reference to an actually delivered artifact.
 */
deliveredArtifact?: string, };
