// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalStage } from "../protocol/ThreadGoalStage";
import type { ThreadGoalStatus } from "./ThreadGoalStatus";

export type ThreadGoalSetParams = { threadId: string, objective?: string | null, status?: ThreadGoalStatus | null, tokenBudget?: number | null, timezone?: string | null, stages?: Array<ThreadGoalStage> | null, };
