// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadGoalStage } from "../protocol/ThreadGoalStage";
import type { GoalQuotaSnapshot } from "./GoalQuotaSnapshot";
import type { ThreadGoalStatus } from "./ThreadGoalStatus";

export type ThreadGoal = { threadId: string, objective: string, status: ThreadGoalStatus, tokenBudget: number | null, tokensUsed: number, timeUsedSeconds: number, createdAt: number, updatedAt: number, timezone: string | null, stages: Array<ThreadGoalStage>, initialQuotaSnapshots: Array<GoalQuotaSnapshot>, initialTokenBudget: number | null, };
